#!/bin/sh
#
#

start() {
	printf "Turning INIT led on: " 
	echo 53 > /sys/class/gpio/export
	echo "out" > /sys/class/gpio/gpio53/direction
	echo 1 > /sys/class/gpio/gpio53/value
	printf "OK\n"
}

stop() {
	printf "Turning INIT led off: "
	echo 53 > /sys/class/gpio/unexport
	printf "OK\n" 
}

restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
